# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Change Number'
        # Default value if no value is explicitly provided
        default: 'CHG00'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
   changeUpdate:
    name: Update
    runs-on: ubuntu-latest
    steps:
     - name: ServiceNow DevOps Change Update
       uses: rapdev-io/sn-devops-change-update@v2.3.1
       with:
          devops-integration-user-name: ${{ secrets.DEVOPS_INTEGRATION_USER_NAME }}
          devops-integration-user-pass: ${{ secrets.DEVOPS_INTEGRATION_USER_PASS }}
          context-github: ${{ toJSON(github) }}
          instance-name: 'dev98557'
          change-state: 'review'
          change-number: 'CHG0030221'
          change-result: 'test'
